---
# tasks file for egeneralov.gitlab

- name: "install : system-wide deps"
  apt:
    name:
      - ca-certificates
      - apt-transport-https
      - debian-archive-keyring
    update_cache: yes
    cache_valid_time: 3600
    state: latest
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2

- name: "configure : apt-key"
  apt_key:
    url: "{{ gitlab_key_url }}"
    state: present
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2
  when: gitlab_key_url is defined

- name: "configure : apt-repo"
  apt_repository:
    repo: "{{ gitlab_repository }}"
    state: present
    filename: gitlab
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2

- name: "install : gitlab-{{ gitlab_revision }}"
  apt:
    name: "gitlab-{{ gitlab_revision }}{% if gitlab_version is defined %}={{ gitlab_version }}{% endif %}"
    state: "{% if gitlab_version is defined %}present{% else %}latest{% endif %}"
    update_cache: yes
    cache_valid_time: 3600
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2

- name: "configure : gitlab.rb"
  template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    backup: yes
  register: tpl

- name: "gitlab-ctl reconfigure"
  shell: gitlab-ctl reconfigure
  when: tpl is changed
  register: task_result
  until: task_result is success
  retries: 2
  delay: 2
