---
# tasks file for egeneralov.gitlab


- name: Install system-wide deps
  apt:
    name:
      - ca-certificates
      - apt-transport-https
      - debian-archive-keyring
    update_cache: yes
    cache_valid_time: 3600
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: apt-key gitlab
  apt_key:
    url: https://packages.gitlab.com/gitlab/gitlab-ee/gpgkey
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: apt-repo gitlab
  apt_repository:
    repo: deb https://packages.gitlab.com/gitlab/gitlab-ce/debian/ stretch main
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: "Install gitlab-ce"
  apt:
    name: "gitlab-ce{% if gitlab_version is defined %}={{ gitlab_version }}{% endif %}"
    state: "{% if gitlab_version is defined %}present{% else %}latest{% endif %}"
#     state: present
    update_cache: yes
    cache_valid_time: 3600
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: gitlab.rb
  template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    backup: yes
  register: tpl

- name: "gitlab-ctl reconfigure"
  shell: gitlab-ctl reconfigure
  when: tpl is changed
  register: task_result
  until: task_result is success
  retries: 2
  delay: 2
