---
# tasks file for egeneralov.gitlab

- name: "check : playbook settings"
  assert:
    that:
      - gitlab_revision in gitlab_supported_revisions

- import_tasks: install.yml

- name: "restore from backup"
  block:
    - name: "check : if already restored"
      stat:
        path: "/var/opt/gitlab/backups/{{ restore.from | basename }}"
      register: backup_file_on_host

    - name: "restore : from backup"
      import_tasks: restore.yml
      when: "backup_file_on_host.stat.islnk is not defined or restore.force"

  when: restore.enabled


- name: "install : backup crontab task"
  cron:
    name: "GitLab backup"
    special_time: "{{ backup.schedule }}"
    job: "{{ __gitlab_backup_cmd__ }}"
  when: backup.enabled

- name: "install : purge duplicate's runners crontab task"
  cron:
    name: "GitLab backup"
    special_time: "{{ backup.schedule }}"
    job: "{{ __gitlab_runners_clean_cmd__ }}"
  when: runners_clean

# TODO: rebuild
- name: "wait : for services"
  wait_for:
    port: "{{ item }}"
    host: "127.0.0.1"
    connect_timeout: 3
    timeout: 60
  with_items:
    - 5000
    - 9229
    - 8080
    - 80
    - 8082
    - 9236
    - 8060
  tags:
    - never
