---
# tasks file for egeneralov.gitlab

- import_tasks: install.yml

- name: Restore from backup
  block:
    - name: Check if already restored
      stat:
        path: "/var/opt/gitlab/backups/{{ restore.from | basename }}"
      register: backup_file_on_host

#     - debug: var=backup_file_on_host
#     - debug: var=restore

    - name: restore from backup
      import_tasks: restore.yml
      when: "backup_file_on_host.stat.islnk is not defined or restore.force"

  when: restore.enabled

- name: Install backup crontab task
  cron:
    name: "GitLab backup"
    special_time: "{{ backup.schedule }}"
    job: "export {% if backup.skip|length > 0 %}SKIP={{ backup.skip | join(',')}} {% endif %}CRON=1 && gitlab-rake gitlab:backup:create{% if backup.autoremove %} && rm /var/opt/gitlab/backups/*.tar{% endif %}"

- name: "Wait for services to be ready"
  wait_for:
    port: "{{ item }}"
    host: "127.0.0.1"
    connect_timeout: 3
    timeout: 60
  with_items:
    - 5000
    - 9229
    - 8080
    - 80
    - 8082
    - 9236
    - 8060
